---
- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 300
    connect_timeout: 5
    pre_reboot_delay: 10
    post_reboot_delay: 30
    test_command: uptime
    msg: "Rebooting to apply proxy settings"