---
- name: Restrict SSH
  hosts:
    - test-k3s
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - firewall
  tasks:
    - name: Delete Allow SSH from LAN
      ansible.builtin.ufw:
        rule: allow
        port: 22
        proto: tcp
        comment: "SSH from LAN"
        direction: in
        src: "{{ network.identifier }}.{{ network.subnets.lan }}"
        delete: yes

    - name: Restrict SSH to allowed subnet
      no_log: true
      ansible.builtin.ufw:
        rule: deny
        port: 22
        proto: tcp
        comment: "Deny SSH from other IPs"
    
    - name: Update UFW policy to deny
      ansible.builtin.ufw:
        policy: deny

    - name: Remove bootstrap user
      ansible.builtin.user:
        name: bootstrap
        state: absent
        remove: yes