---
- name: Restrict SSH
  hosts:
    - test-k3s
    - game-k3s
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - firewall
  vars_files:
    - roles/user/vars/main.yml # For authorized_keys
  tasks:
    - name: Delete Allow SSH from LAN
      ansible.builtin.ufw:
        rule: allow
        port: 22
        proto: tcp
        comment: "SSH from LAN"
        direction: in
        src: "{{ network.identifier }}.{{ network.subnets.lan }}"
        delete: yes

    - name: Restrict SSH to allowed subnet
      no_log: true
      ansible.builtin.ufw:
        rule: deny
        port: 22
        proto: tcp
        comment: "Deny SSH from other IPs"
    
    - name: Update UFW policy to deny
      ansible.builtin.ufw:
        policy: deny

    - name: Remove bootstrap user
      ansible.builtin.user:
        name: bootstrap
        state: absent
        remove: yes
    
    - name: Update authorized keys
      when: item.authorized_keys is defined
      ansible.builtin.copy:
        content: "{{ authorized_keys }}"
        dest: "/home/{{ user_name }}/.ssh/authorized_keys"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: 0600
      with_items:
        - user_name: devops
          authorized_keys: "{{ ssh.devops.cert }}"
        - user_name: ansible
          authorized_keys: "{{ ssh.ansible.cert }}"