---
- name: Install yum-utils
  hosts:
    - bastions
  become: yes
  gather_facts: yes
  tags:
    - yum
  tasks:
    - name: Install yum-utils
      ansible.builtin.command: |
        yum install -y yum-utils
      register: yum_install
      changed_when: yum_install.stdout != 'Nothing to do.'

# - name: Configure SSH keys for Bootstrap user

# - name: Configure SSH settings

- name: Create Ansible User
  hosts:
    - tower
  become: yes
  gather_facts: yes
  tags:
    - ansible
    - ssh
    - users
  vars:
    can_sudo: no
    user_name: ansible
  roles:
    - user

# - name: Configure Ansible SSH keys

- name: Create DevOps User
  hosts:
    - bastions
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - users
  vars:
    can_sudo: yes
    user_name: devops
    user_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36383434663166646630313363393337396363623930656363633036666662313338326336663037
      3137646561663732326366646538396632613561646334630a633532366361663832653535333832
      61336636363230343361326266393165626333366534323863393637313637326533356661636265
      3232373762656338650a393835306636363561343265336563666637343461396432306263623732
      3238
  roles:
    - user

# - name: Configure DevOps SSH keys

- name: Configure internet proxy
  hosts:
    - bastions
  become: yes
  gather_facts: yes
  tags:
    - proxy
  roles:
    - use-proxy

- name: Configure firewall
  hosts:
    - bastions
  become: yes
  gather_facts: yes
  tags:
    - firewall
  roles:
    - bastion-firewall

# - name: Setup github actions runner

- hosts:
    - bastions
  tasks:
    - debug:
        msg: "Validate the server and remove the bootstrap user if all validations are successful"