---
- name: Install yum-utils
  hosts:
    - bastions
  become: yes
  gather_facts: yes
  tags:
    - yum
  tasks:
    - name: Install yum-utils
      ansible.builtin.command: |
        yum install -y yum-utils
      register: yum_install
      changed_when: yum_install.stdout != 'Nothing to do.'

- name: Configure SSH keys for Bootstrap user
  hosts:
    - bastions
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - users
    - bootstrap
  vars:
    can_sudo: yes
    user_name: bootstrap
    user_password: "{{ bootstrap_password }}"
    authorized_keys: |
      {{ ssh.gamer.windows }}
      {{ ssh.gamer.linux }}
  roles:
    - user

- name: Configure SSH settings
  hosts:
    - bastions
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - ssh-cfg
  roles:
    - ssh

- name: Create Ansible User
  hosts:
    - tower
  become: yes
  gather_facts: yes
  tags:
    - ansible
    - ssh
    - users
  vars:
    can_sudo: no
    user_name: ansible
    ssh_cert: "{{ ssh.ansible.cert }}"
    ssh_key: "{{ ssh.ansible.key }}"
  roles:
    - user

- name: Create DevOps User - Tower
  hosts:
    - tower
  become: yes
  gather_facts: yes
  tags:
    - devops
    - ssh
    - users
  vars:
    can_sudo: yes
    user_name: devops
    user_password: "{{ ssh.devops.password }}"
    authorized_keys: |
      {{ ssh.devops.cert}}
  roles:
    - user

- name: Create DevOps User - Bastion
  hosts:
    - tunnel
    # - ui
  become: yes
  gather_facts: yes
  tags:
    - devops
    - ssh
    - users
  vars:
    can_sudo: yes
    user_name: devops
    user_password: "{{ ssh.devops.password }}"
    ssh_cert: "{{ ssh.devops.cert }}"
    ssh_key: "{{ ssh.devops.key }}"
    authorized_keys: |
      {{ ssh.gamer.windows }}
      {{ ssh.gamer.linux }}
  roles:
    - user

- name: Configure internet proxy
  hosts:
    - bastions
  become: yes
  gather_facts: yes
  tags:
    - proxy
  roles:
    - use-proxy

- name: Configure firewall
  hosts:
    - bastions
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - firewall
  roles:
    - bastion-firewall

- name: Allow SSH from Bastion to Tower
  hosts:
    - tower
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - firewall
  tasks:
    - name: allow ssh and cockpit inbound from Bastions
      ansible.builtin.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        from_ip: "{{ network.identifier }}.{{ network.subnets.lan }}"
        comment: "{{ item.comment }}"
      with_items:
        - { port: 22, proto: 'tcp', comment: 'SSH' }
        - { port: 9090, proto: 'tcp', comment: 'Cockpit' }

#TODO: Docker Actions Runner

- name: Setup GitHub Actions Runner
  hosts:
    - tower
  become: yes
  gather_facts: yes
  tags:
    - agent
  vars:
    agent_directory: /opt/gh-actions-runner
    agent_user: ansible
    agent_url: https://github.com/espresso-software
    gh_token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66316365653831613531623562306663393136616438333335633436633137323065396563376532
      3737343737303733643562306362626630346430613338310a316365336233303165306463383430
      37636231633632383061613761623137383132373865303538393230353236336530363934383361
      3865313965333665650a333364633961333237623339663066356534316134323731346435333763
      37663866616237646639383962363431353933393530383333393935346534393265393065323633
      30373933336630386634643035636135336436373730363432623038613461353261306337353937
      34663266663734663062666362666632356530386465336563343734386161373665363435356466
      38396165616234666164326537616139366531386336666331636130343030623238643039366363
      3938
  roles:
    - agent

- hosts:
    - bastions
  tasks:
    - debug:
        msg: "Validate the server and remove the bootstrap user if all validations are successful"