---
- name: Use proxy
  hosts:
    - towers
  become: true
  gather_facts: true
  tags:
    - proxy
  roles:
    - use-proxy

- name: Install yum-utils
  hosts:
    - towers
  become: true
  gather_facts: true
  tags:
    - yum
  tasks:
    - name: Install yum-utils
      ansible.builtin.command: |
        yum install -y \
          yum-utils
      register: yum_install
      changed_when: yum_install.stdout != 'Nothing to do.'

- name: Configure SSH keys for Bootstrap user
  hosts:
    - towers
  become: true
  gather_facts: true
  tags:
    - ssh
    - users
    - bootstrap
  vars:
    can_sudo: true
    user_name: bootstrap
    user_password: "{{ bootstrap_password }}"
    authorized_keys: |
      {{ ssh.devops.cert }}
  roles:
    - user

- name: Configure SSH settings
  hosts:
    - towers
  become: true
  gather_facts: true
  tags:
    - ssh
    - ssh-cfg
  roles:
    - ssh

- name: Create Ansible User - Tower
  hosts:
    - towers
  become: true
  gather_facts: true
  tags:
    - ansible
    - ssh
    - users
  vars:
    can_sudo: false
    user_name: ansible
    ssh_cert: "{{ ssh.ansible.cert }}"
    ssh_key: "{{ ssh.ansible.key }}"
  roles:
    - user

- name: Create DevOps User - Tower
  # only allow ssh from the tunnel and ui bastions
  hosts:
    - towers
  become: true
  gather_facts: true
  tags:
    - devops
    - ssh
    - users
  vars:
    can_sudo: true
    user_name: devops
    user_password: "{{ ssh.devops.password }}"
    authorized_keys: |
      {{ ssh.devops.cert }}
  roles:
    - user

# - name: Create DevOps User - UI Bastion
#   # only allow ssh from the ui bastions to the lab servers
#   hosts:
#     - ui
#   become: true
#   gather_facts: true
#   tags:
#     - devops
#     - ssh
#     - users
#   vars:
#     can_sudo: true
#     user_name: devops
#     user_password: "{{ ssh.devops.password }}"
#     ssh_cert: "{{ ssh.devops.cert }}"
#     ssh_key: "{{ ssh.devops.key }}"
#   roles:
#     - user

# FIXME: RDP Server
# - name: Allow RDP from LAN
#   hosts:
#     - ui
#   become: yes
#   gather_facts: yes
#   tags:
#     - rdp
#     - firewall
#   tasks:
#     - name: allow RDP inbound from LAN
#       ansible.builtin.ufw:
#         rule: allow
#         direction: "{{ item.direction | default('in') }}"
#         port: "{{ item.port }}"
#         proto: 'tcp'
#         from_ip: "{{ item.subnet }}"
#         comment: "{{ item.comment }}"
#       with_items:
#         - { port: 3389, subnet: "{{ network.identifier }}.{{ network.subnets.lan }}", comment: 'RDP' }
#         - { port: 5901, subnet: "127.0.0.1", comment: 'RDP - VNC' }
#         - { port: 5901, subnet: "{{ ansible_host }}", comment: 'RDP - VNC', direction: 'out'}
#     - name: Install RDP Server
#       ansible.builtin.command: |
#         yum install -y \
#           tigervnc-server \
#           xrdp \
#           @gnome-desktop \
#           policycoreutils-python-utils
#       register: rdp_install
#       changed_when: rdp_install.stdout != 'Nothing to do.'
#     - name: Configure VNC Server
#       ansible.builtin.copy:
#         remote_src: yes
#         src: /lib/systemd/system/vncserver@.service
#         dest: /etc/systemd/system/vncserver@.service
#         owner: root
#         group: root
#         mode: 0644
#     - name: Create VNC Directory - Devops
#       ansible.builtin.file:
#         path: /home/devops/.vnc
#         state: directory
#         owner: devops
#         group: devops
#         mode: 0755
#     - name: Configure VNC Startup - Devops
#       ansible.builtin.copy:
#         content: |
#           #!/bin/sh
#           env GNOME_SHELL_SESSION_MODE=classic dbus-launch --exit-with-session /usr/bin/gnome-session
#         dest: /home/devops/startwm.sh
#         owner: devops
#         group: devops
#         mode: 0755
#     - name: Set XVNC Configuration
#       ansible.builtin.lineinfile:
#         path: /etc/xrdp/xrdp.ini
#         line: "{{ item.name }}={{ item.value }}"
#         regex: '^{{ item.name }}='
#         state: present
#       with_items:
#         - name: port
#           value: -1
#         - name: IP
#           value: "127.0.0.1"
#     - name: Set SELinux policies
#       become: yes
#       ansible.builtin.command: "{{ item }}"
#       with_items:
#         - chcon --type=bin_t /usr/sbin/xrdp
#         - chcon --type=bin_t /usr/sbin/xrdp-sesman
#     - name: Start RDP Server
#       ansible.builtin.systemd:
#         name: xrdp
#         enabled: yes
#         state: started
#       changed_when: false

# TODO: Docker Actions Runner

- name: Setup GitHub Actions Runner
  hosts:
    - towers
  become: true
  gather_facts: true
  tags:
    - agent
  vars:
    agent_directory: /opt/gh-actions-runner
    agent_user: ansible
    agent_url: https://github.com/espresso-software
    gh_token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36653863346139386163373535613665653932656261303463303933343235623233363534646134
      6636316337323633656236323831366438326538373564640a393233623232626238613834626363
      38663835666264613638323864653562633439623261353439313063623232363839643331613036
      6339316432323137310a376365613162376461646231636464656161613633633036386634323730
      61376234326235623764626664336338336465633838353439643831633135343961666165313432
      32303332666332663364393638313066336436663434633462323936623030626332313164613965
      33616437613063366163626433643134336163653766663536383935666137623430393834353237
      66393665643931323266653061653665623038376338383530333730373061306532633661373237
      3331
  roles:
    - agent

- name: Validation reminder
  hosts:
    - towers
  tasks:
    - name: Validate the server and remove the bootstrap user if all validations are successful
      ansible.builtin.debug:
        msg: "Validate the server and remove the bootstrap user if all validations are successful"
      failed_when: false
