---
- name: Use proxy
  hosts:
    - desktops
  become: true
  gather_facts: true
  tags:
    - proxy
  roles:
    - use-proxy

- name: Install Dependencies
  hosts:
    - desktops
  become: true
  gather_facts: true
  tags:
    - dependencies
  tasks:
    - name: Install dependencies
      ansible.builtin.dnf:
        name:
          - ansible
          - git
          - python3-pip
          - sshpass
        state: present

- name: Create Ansible user
  hosts:
    - desktops
  become: true
  gather_facts: true
  tags:
    - ssh
    - ansible
  vars:
    can_sudo: true
    user_name: ansible
    authorized_keys: "{{ ssh.ansible.cert }}"
    user_password: "{{ ssh.ansible.password }}"
  roles:
    - user

- name: Create Devops user
  hosts:
    - desktops
  become: true
  gather_facts: true
  tags:
    - ssh
    - devops
  vars:
    can_sudo: true
    user_name: devops
    authorized_keys: "{{ ssh.yubikey.black }}"
    user_password: "{{ ssh.devops.password }}"
    ssh_cert: "{{ ssh.devops.cert }}"
    ssh_key: "{{ ssh.devops.key }}"
  roles:
    - user

- name: Configure SSH settings
  hosts:
    - desktops
  become: true
  gather_facts: true
  vars:
    password_authentication: false
  tags:
    - ssh
    - ssh-cfg
  roles:
    - ssh

- name: Setup Bash Aliases
  hosts:
    - desktops
  become: true
  become_user: devops
  gather_facts: true
  tags:
    - bash
  vars:
    aliases:
      - name: ll
        value: "ls -la"
      - name: g
        value: "git"
      - name: gco
        value: "git checkout"
      - name: ga
        value: "git add"
      - name: gcm
        value: "git commit -m"
      - name: gbr
        value: "git branch"
      - name: gst
        value: "git status"
  tasks:
    - name: Create Bash Aliases
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "alias {{ item.name }}='{{ item.value }}'"
        state: present
      loop: "{{ aliases }}"

- name: Setup Git Configuration
  hosts:
    - desktops
  become: true
  become_user: devops
  gather_facts: true
  tags:
    - git
  tasks:
    - name: Configure Git User
      ansible.builtin.lineinfile:
        path: ~/.gitconfig
        line: |
          [user]
            name = Ty Foster
            email = tyfoster@outlook.com
          [alias]
            co = checkout
            br = branch
            cm = commit -m
            st = status
            a = add
        create: true
        mode: "0644"
        state: present

- name: Setup Docker
  hosts:
    - desktops
  become: true
  gather_facts: true
  vars:
    docker_users:
      - ansible
      - devops
  tags:
    - docker
  roles:
    - docker
