---
- name: Ping all hosts
  hosts:
    - all
  gather_facts: no
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
      register: result
      failed_when: false
    - name: Print result
      ansible.builtin.debug:
        var: result