---
- name: Configure devops user
  hosts:
    - lab
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - devops
  vars_files:
    - roles/user/vars/main.yml
  vars:
    can_sudo: yes
    user_name: devops
    user_password: "{{ devops_password }}"
  roles:
    - user

- name: Setup devops SSH configuration
  hosts:
    - lab
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - devops
  vars_files:
    - roles/ssh/vars/main.yml
  vars:
    user_name: devops
    authorized_keys: "{{ ssh.devops.cert }}"
  roles:
    - ssh

- name: Restrict SSH
  hosts:
    - lab
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - devops
  tasks:
    - name: Restrict SSH to allowed subnet
      no_log: true
      ansible.builtin.ufw:
        rule: deny
        port: 22
        proto: tcp
        comment: "Deny SSH from other IPs"

    - name: Update UFW policy to deny
      ansible.builtin.ufw:
        policy: deny