---
- name: Restrict SSH
  hosts:
    - all
  become: true
  gather_facts: true
  tags:
    - ssh
  tasks:
    - name: Remove bootstrap user
      ansible.builtin.user:
        name: bootstrap
        state: absent
        remove: true

- name: Crontab for clearing RAM cache
  hosts:
    - all
  become: true
  gather_facts: true
  tags:
    - system
    - ram
  tasks:
    - name: Ensure cron job to clear RAM cache every 15 minutes is present
      when: ansible_hostname is match(".*vl.*")
      ansible.builtin.cron:
        name: "Clear RAM cache every 15 minutes"
        minute: "*/15"
        hour: "*"
        job: "/usr/bin/sync; /usr/sbin/sysctl -w vm.drop_caches=3"
        state: present
