---
- name: Restrict SSH
  hosts:
    - all
  become: true
  gather_facts: true
  tags:
    - ssh
  tasks:
    - name: Kill all processes running under bootstrap user
      ansible.builtin.command:
        cmd: killall -u bootstrap
      changed_when: false
      failed_when: false

    - name: Remove bootstrap user
      ansible.builtin.user:
        name: bootstrap
        state: absent
        remove: true

<<<<<<< HEAD
- name: Disable firewalld
=======
- name: Crontab for clearing RAM cache
>>>>>>> 9d763c4 (Feature/ansible swarm (#29))
  hosts:
    - all
  become: true
  gather_facts: true
  tags:
<<<<<<< HEAD
    - firewall
  tasks:
    - name: Disable and stop firewall
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'Rocky'
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false
=======
    - system
    - ram
  tasks:
    - name: Ensure cron job to clear RAM cache every 15 minutes is present
      when: ansible_hostname is match(".*vl.*")
      ansible.builtin.cron:
        name: "Clear RAM cache every 15 minutes"
        minute: "*/15"
        hour: "*"
        job: "/usr/bin/sync; /usr/sbin/sysctl -w vm.drop_caches=3"
        state: present
>>>>>>> 9d763c4 (Feature/ansible swarm (#29))
