---
- name: Setup SSH configuration
  hosts:
    - lab
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - ssh-cfg
  roles:
    - ssh

- name: Restrict SSH
  hosts:
    - lab
  become: yes
  gather_facts: yes
  tags:
    - ssh
    - devops
  vars_files:
  - roles/user/vars/main.yml # For authorized_keys
  tasks:
    - name: Restrict SSH to allowed subnet
      no_log: true
      ansible.builtin.ufw:
        rule: deny
        port: 22
        proto: tcp
        comment: "Deny SSH from other IPs"

    - name: Update UFW policy to deny
      ansible.builtin.ufw:
        policy: deny
    
    - name: Update authorized keys
      when: item.authorized_keys is defined
      ansible.builtin.copy:
        content: "{{ authorized_keys }}"
        dest: "/home/{{ user_name }}/.ssh/authorized_keys"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: 0600
      with_items:
        - user_name: devops
          authorized_keys: "{{ ssh.devops.cert }}"
        - user_name: ansible
          authorized_keys: "{{ ssh.ansible.cert }}"         