---
- name: Restrict SSH
  hosts:
    - all
  become: true
  gather_facts: true
  tags:
    - ssh
  tasks:
    - name: Remove bootstrap user
      ansible.builtin.user:
        name: bootstrap
        state: absent
        remove: true

- name: Disable firewalld
  hosts:
    - all
  become: true
  gather_facts: true
  tags:
    - firewall
  tasks:
    - name: Disable and stop firewall
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'Rocky'
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false
