---
- name: Networking configuration
  hosts:
    - pis
  become: true
  gather_facts: true
  tags:
    - network
  tasks:
    - name: Configure the hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Expand filesystem
      ansible.builtin.command:
        cmd: >
          rootfs-expand
      changed_when: false

    - name: Add VLAN connection
      changed_when: false
      ansible.builtin.command:
        cmd: >
          nmcli con add type vlan
          con-name vlan
          ifname vlan
          vlan.parent {{ ethernet.device }}
          vlan.id {{ network.vlan }}

    - name: NMCLI - Configure Ethernet interface
      changed_when: false
      ansible.builtin.command:
        cmd: >
          nmcli con mod vlan
          ipv4.gateway '{{ network.gateway }}'
          ipv4.addresses {{ static_ip }}/{{ network.subnet }}
          ipv4.dns '{{ network.gateway }},1.1.1.1,1.0.0.1'
          ipv4.method manual

    - name: NMCLI - Activate the VLAN connection
      changed_when: false
      ansible.builtin.command:
        cmd: >
          nmcli con up vlan

    - name: NMCLI - Remove default connection
      changed_when: false
      ansible.builtin.command:
        cmd: >
          nmcli con delete 'Wired connection 1'
      ignore_errors: true
