---
- name: Install Dependencies
  ansible.builtin.apt:
    name:
      - keepalived
      - squid
    state: latest

- name: Configure Squid
  notify: restart squid
  ansible.builtin.template:
    dest: /etc/squid/squid.conf
    src: squid.conf.j2
    owner: root
    group: root
    mode: 0640

- name: Enable Squid
  ansible.builtin.systemd:
    name: squid
    enabled: yes
    state: started

- name: Configure Keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0640
  notify: Restart Keepalived

- name: Configure HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0640
  notify: Restart HAProxy