---
- name: restart ssh
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: yes

- name: compile selinux policy
  ansible.builtin.command: checkmodule -M -m -o /etc/selinux/local/google-authenticator.mod /etc/selinux/local/google-authenticator.te
  notify: semodule_package
    
- name: semodule_package
  ansible.builtin.command: semodule_package -o /etc/selinux/local/google-authenticator.pp -m /etc/selinux/local/google-authenticator.mod
  notify: semodule

- name: semodule
  ansible.builtin.command: semodule -i /etc/selinux/local/google-authenticator.pp
  notify: restart ssh