---
- name: restart squid
  ansible.builtin.systemd:
    name: squid
    state: restarted
    enabled: yes

- name: Restart Keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: yes