---
- name: Check for 50-cloud-init.yaml
  ansible.builtin.stat:
    path: /etc/netplan/50-cloud-init.yaml
  register: netplan_file

- name: Set netplan file permissions
  when: netplan_file.stat.exists
  ansible.builtin.file:
    path: /etc/netplan/50-cloud-init.yaml
    owner: root
    group: root
    mode: 0600

- name: Set static ip
  ansible.builtin.copy:
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          {{ ethernet.device }}:
            dhcp4: false
        vlans:
          vlan:
            id: {{ network.vlan_id }}
            link: {{ ethernet.device }}
            addresses:
              - "{{ ansible_hostname }}/{{ network.subnet }}"
            routes:
              - to: default
                via: "{{ network.gateway }}"
            nameservers:
              addresses:
                - "{{ network.dns1 }}"
                - "{{ network.dns2 }}"
                - 1.1.1.1
                - 1.0.0.1
    dest: /etc/netplan/99-nodecfg.yaml
  notify: apply netplan