name: Developer deployment

on:
    push:
        branches:
            - '**'
        paths:
            - 'developer.yml'
            - .github/workflows/developer.yml
            - roles/ssh/**
            - roles/use-proxy/**
            - roles/user/**
jobs:
  deploy:
    runs-on:
        - self-hosted
        - ansible

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      - name: Run post provisioning playbook
        uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: desktops.yml
          inventory_path: inventory/hosts.yml #bootstrap.yml
          hosts: developer
          tags: all