# This is a basic workflow to help you get started with Actions

name: Poststrap

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      hosts:
        description: 'Hosts to run the playbook on'
        required: true
        default: 'all'
      hosts_file:
        description: 'Hosts file to use'
        required: true
        type: choice
        options:
          - hosts.ini
          - hosts.yml
      playbook:
        description: 'Playbook to run'
        required: true
        type: choice
        options:
          - ansible.yml
          - poststrap.yml

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ['self-hosted', 'ansible']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run post provisioning playbook
        run: |
          echo "${{ secrets.VAULT_DECRYPT_TOKEN }}" > /tmp/vault_pass
          ansible-playbook ${{ github.event.inputs.playbook }} --vault-password-file /tmp/vault_pass \
            -i inventory/${{ github.event.inputs.hosts_file }} \
            -l ${{ github.event.inputs.hosts }}

      # Always removes vault password
      - name: Remove vault pass
        if: always()
        run: |
          rm /tmp/vault_pass
        
